GET http://localhost:8080/users/creativexvc/ads/1


###

POST http://localhost:8080/users/creativexvc/ads
Content-Type: application/json

{
  "title": "Tytuł ogłoszenia",
  "description": "Opis ogłoszenia.",
  "category": "Motoryzacja"

}

###

GET http://localhost:8080/users/creativexvc/ads


###

GET http://localhost:8080/users/creativexvc/ads/9

###

PUT http://localhost:8080/users/creativexvc/ads/9
Content-Type: application/json

{
  "title": "Opel Kadet - jednak zawodna jednostka",
  "description": "Opel Kadet na części."
}

###

GET http://localhost:8080/users/creativexvc/ads/9

###

POST http://localhost:8080/ads/
Content-Type: application/json

{
  "title": "Nowe ogłoszenie",
  "description": "Opis nowego ogłoszenia",
  "category": "Motoryzacja",
  "user": "creativexvc"
}

###

GET http://localhost:8080/ads

###

PUT http://localhost:8080/ads/2
Content-Type: application/json

{
  "title": "Audi limuzyna D3 dziecina",
  "description": "mozna, jak najbardziej"
}

###
GET http://localhost:8080/categories

###

POST http://localhost:8080/categories
Content-Type: application/json

{
  "name": "Praca"
}

###

PUT http://localhost:8080/categories/4
Content-Type: application/json

{
"name": "Edukacja"
}

###

DELETE  http://localhost:8080/categories/4


###

GET http://localhost:8080/categories/Motoryzacja